version: '3.7'

services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=mfa_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  application:
    build:
      context: .
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DATABASE_HOST=${DATABASE_HOST}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
    volumes:
      - ./logs:/logs
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge